# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  apikey:  # id of input
    description: 'API Key'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker-compose'
  args:
    - ${{ inputs.apikey }}