on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Blazemeter test
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          apikey: 'Mona the Octocat'
      # Use the output from the `hello` step
